[build]
  ignore = "/bin/false"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[edge_functions]]
  path = "/*"
  function = "entry.netlify-edge"

[context.production.environment]
  QUIZ_URL = "${QUIZ_URL}"